server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:E:\HOME\chatico\config-service\src\main\resources\config\userchats.yml

